### PR TITLE
Mitigate PHP Bug with Blank Session Id

### PR DESCRIPTION
**Pull request by tegansnyder**
References this issue https://github.com/kalenjordan/magehero/issues/89

### CODE REVIEW

**Comment by kalenjordan** [comment]
Thanks @tegansnyder - looking good!  Should be able to test this out today or tomorrow.  Unless @bobbyshaw gets to it first.

**Comment by bobbyshaw** [comment]
This worked all fine testing locally and on staging.  Thanks for reporting, hunting the problem down and fixing @tegansnyder!

**Comment by tegansnyder** [comment]
@bobbyshaw @kalenjordan now i just need to find time to submit a feature request. Whats the best method for testing locally? Can I get a dev db pull?

**Comment by kalenjordan** [comment]
Deployed.  Maybe @bobbyshaw can hook you up with a stripped dump at some point?

**Pull request merged**
